services:
  zquic-verify:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      network: host
    network_mode: host
    working_dir: /workspace
    volumes:
      - ..:/workspace
      - ${HOST_ZIG_PATH:-/opt/zig-dev}:/opt/zig:ro
    tty: true
    stdin_open: true
  zquic-interop:
    build:
      context: ..
      dockerfile: docker/Dockerfile.interop
      network: host
    network_mode: host
    working_dir: /workspace
    volumes:
      - ..:/workspace
      - ${HOST_ZIG_PATH:-/opt/zig-dev}:/opt/zig:ro
    tty: true
    stdin_open: true
