FROM debian:trixie-slim

ENV DEBIAN_FRONTEND=noninteractive
ARG RUST_VERSION=1.88.0
ARG QUICHE_REF=0.29.2
ARG MSQUIC_REF=v2.5.9
ENV RUSTUP_HOME=/usr/local/rustup
ENV CARGO_HOME=/usr/local/cargo
ENV CARGO_BUILD_JOBS=4
ENV CMAKE_BUILD_PARALLEL_LEVEL=4
ENV MAKEFLAGS=-j4
ENV PATH=/workspace/docker/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        bash \
        ca-certificates \
        cmake \
        curl \
        git \
        build-essential \
        libclang-dev \
        liblttng-ust-dev \
        libnuma-dev \
        lttng-tools \
        ninja-build \
        perl \
        pkgconf \
        python3 \
        python3-aioquic \
        rustup \
        ngtcp2-client \
        ngtcp2-server \
        libngtcp2-dev \
        libngtcp2-crypto-gnutls-dev \
        libnghttp3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup toolchain install "$RUST_VERSION" --profile minimal \
    && rustup default "$RUST_VERSION"

RUN git clone --depth 1 --branch "$QUICHE_REF" https://github.com/cloudflare/quiche.git /opt/src/quiche \
    && cargo build --manifest-path /opt/src/quiche/Cargo.toml --release \
        -p quiche_apps --bin quiche-client --bin quiche-server \
    && install -m 0755 /opt/src/quiche/target/release/quiche-client /usr/local/bin/quiche-client \
    && install -m 0755 /opt/src/quiche/target/release/quiche-server /usr/local/bin/quiche-server \
    && rm -rf /opt/src/quiche "$CARGO_HOME/registry" "$CARGO_HOME/git"

RUN git clone --depth 1 --branch "$MSQUIC_REF" --recurse-submodules https://github.com/microsoft/msquic.git /opt/src/msquic \
    && cmake -S /opt/src/msquic -B /opt/src/msquic/build -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DQUIC_BUILD_TOOLS=ON \
        -DQUIC_ENABLE_LOGGING=OFF \
        -DQUIC_TLS_LIB=quictls \
    && cmake --build /opt/src/msquic/build --target quicinterop quicinteropserver quicsample \
    && find /opt/src/msquic/build -type f -name 'libmsquic.so.*' -exec install -m 0755 {} /usr/local/lib/libmsquic.so.2.5.9 \; -quit \
    && ln -sf libmsquic.so.2.5.9 /usr/local/lib/libmsquic.so.2 \
    && ln -sf libmsquic.so.2.5.9 /usr/local/lib/libmsquic.so \
    && ldconfig \
    && find /opt/src/msquic/build -type f -perm /111 -name quicinterop -exec install -m 0755 {} /usr/local/bin/quicinterop \; -quit \
    && find /opt/src/msquic/build -type f -perm /111 -name quicinteropserver -exec install -m 0755 {} /usr/local/bin/quicinteropserver \; -quit \
    && find /opt/src/msquic/build -type f -perm /111 -name quicsample -exec install -m 0755 {} /usr/local/bin/quicsample \; -quit \
    && rm -rf /opt/src/msquic

WORKDIR /workspace

CMD ["bash"]
